
format = """
$character\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell"""

command_timeout = 5000
add_newline = false

[username]
show_always = true
format = '[\[$user\] ](bold green)'

# [hostname]
# ssh_only = false
# format = "[$hostname]($style)"
# trim_at = "-"
# style = "bold dimmed red"
# disabled = false
[directory]
read_only = " "
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo

[line_break]
disabled = true # do not separate prompt into 2 lines

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (= 10 sec)
format = "took [$duration ]($style)"

############
# Disabled #
############

[package]
disabled = true

[gcloud]
disabled = true

[aws]
disabled = true
